### ISSUE TITLE
Container not storing data.

### ISSUE THREAD

**Issue by ShockCharge** [OmerBenGera/WildInspect#1]
https://imgur.com/a/qOQRhrU

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
What CoreProtect version are you using and which server version do you run?

**Comment by ShockCharge** [comment]
CoreProtect 19.4
Tuinity Build 179 (1.16.4)

**Comment by OmerBenGera** [comment]
Still works for me.
When you run /co i, are there any container transactions?

**Comment by OmerBenGera** [comment]
?

**Comment by So1embum** [comment]
I'm getting the same issue. I'm running the latest build of all three plugins and testing on an unopped account. My claiming plugins is Lands. Why I /co i the container, I do see container transactions.

**Comment by OmerBenGera** [comment]
Hey, mind tagging me on Discord? I'll need a copy of Lands to test this out

**Comment by OmerBenGera** [comment]
I couldn't replicate the issue, and no response was sent here.
Let me know how to replicate it

**Comment by Firestone82** [comment]
I have normal CoreProtect on server, added fresh WildInspect, but when i click somewhere where something should be. Nothing is displayed, will shoot you a video if you need.

**Comment by Firestone82** [comment]
Hi, here you can find video about that problem, one problem is in Issue #2 throwing warns about that page 0. Second one is. that it wont show anything. Hope that helps.. 

https://user-images.githubusercontent.com/57676764/111069734-b46b6a80-84ce-11eb-9887-da33c74d7bc4.mp4

**Comment by OmerBenGera** [comment]
@Firestone82 This issue might be caused because of #2 . Check out if the other issue is fixed, and if it does, check if this issue is fixed as well.

**Comment by Firestone82** [comment]
Works, thanks.
